### PR TITLE
Added Flare Icon (A Signal Desktop Client)

### PR DESCRIPTION
**Pull request by Crazyroostereye1**
Added the Scalable and 16 of Flare

Here is the Flare Project:
https://gitlab.com/schmiddi-on-mobile/flare

### CODE REVIEW

**Comment by SylEleuth** [comment]
`16` - icon is misaligned, there should be 1px space on top and bottom; other elements should be aligned with a grid; move it outside of the group and combine all elements to one.
`scalable` - looks good, I would personally optimize the star but it's not a big thing, background is too dark, I reserve darkest colors (#1d2021, #282828) to specific situations, usually I make gradient slightly lighter at the top (change it to #3c3836 or #504945, whichever looks better)

**Comment by Crazyroostereye1** [comment]
Added the fixes

**Comment by SylEleuth** [comment]
Saying "aligning to a grid" I meant that everything should be aligned, not only top, including a star (and round corner's start points).

**Comment by SylEleuth** [comment]
Screenshot_2024-11-06-121209

**Comment by SylEleuth** [comment]
On the surface it looks ok now, but You have to clean it up, because it's a little bit messy.

**Comment by Crazyroostereye1** [comment]
Sorry, was a bit busy lately. Fixed the Star a bit up. Did not Notice at first that it was that Chaotic.

**Comment by SylEleuth** [comment]
Almost there.

One double node to remove:
Screenshot_2024-11-11-102630

"Corners" have irregular shape and going out of the page:
Screenshot_2024-11-11-102741

**Comment by SylEleuth** [comment]
Not enough. Still going outside of the page.

**Comment by SylEleuth** [comment]
You just resized it to fit a page, but in the same time made it slightly smaller and not aligned to a grid. Also top of the star is not round.

**Comment by RustoMCSpit** [comment]
> scalable - looks good, I would personally optimize the star but it's not a big thing, background is too dark, I reserve darkest colors (#1d2021, #282828) to specific situations, usually I make gradient slightly lighter at the top (change it to #3c3836 or #504945, whichever looks better)

has this been fixed

**Comment by Crazyroostereye1** [comment]
No, sorry was busy the Past 2 Weeks and couldn't Continue working on it. Should be better Next Week

**Pull request closed without merging**
