### PR TITLE
add F3D app icons

### PR DESCRIPTION
**Pull request by mojamuto**
I have added the icons of the F3D program: https://github.com/f3d-app/f3d/tree/master

It is the first one I do, please take your time to check that everything is fine and nothing is missing.
The additions are:
gruvbox-plus-icon-pack/apps/16/f3d.svg
gruvbox-plus-icon-pack/apps/scalable/f3d.svg
gruvbox-plus-icon-pack/apps/symbolic/f3d-symbolic.svg

This is the original icon: https://github.com/f3d-app/f3d/blob/master/resources/logo.svg

Do you prefer that I make the icons with the 3 base icons, for you to choose?

### CODE REVIEW

**Comment by SylEleuth** [comment]
Instead of commenting each icon separately I will do it here so it will be easier to explain some things.
1. General rule for app/16 is that there should be 1px of padding. Please look at the other icons in that folder.
2. Scalable ones don't have any padding restrictions and it all depends on the size of the icon (if it's wide or narrow). It's just need to "look good".
3. Please center icons in the middle of the page.
4. Scalable is a little messy. It has copies of different elements hidden underneath. After revealing it looks like this:
F3D
5. Scalable colors are a little bit off. Please refer to the pallets on the [gruvbox page](https://github.com/morhetz/gruvbox). Original icon has dark colors so I personally wouldn't go with lightest "row". Also gruvbox green is not suited for this and I would use aqua. So my colors would be red - #cc241d (have You noticed that Your red is not even in the pallet) , green - #689d6a and blue - #076678. Bright base looks the best for it.
5. And the last one is saving. In Inkscape use "optimised SVG". Those are settings that I use:
Screenshot_20230424_133413
Screenshot_20230424_133424
Screenshot_20230424_133455
If You are using different program You should also use Scour. Although I've never used it as a standalone but I believe those options would be the same.

**Comment by mojamuto** [comment]
I'm using inkscape but as you can see, I'm new...
The colors I have cheated a bit and instead of looking in the gruvbox palette, I have taken them from other icons in the same folder.
Thank you very much for taking the time to explain it to me, I'll fix it

**Comment by SylEleuth** [comment]
> The colors I have cheated a bit and instead of looking in the gruvbox palette, I have taken them from other icons in the same folder.

Some icon might have color gradient so it's always a better choice to use pallet. With exception of symbolic icons which have only few colors. I'm using gruvbox for so long now that I know most of the colors hex codes and yet I always check if the one I picked match.
Do you remember which icons You used to pick colors? I just want to check. There are still errors here and there and I'm sure I've missed something.

> Thank you very much for taking the time to explain it to me, I'll fix it

No worries. It looks like I should write a wiki page for contributors. I've never expected that I'll have any.

**Comment by mojamuto** [comment]
If I have understood everything correctly, everything should be solved, I have redone the icons

**Comment by mojamuto** [comment]
You are right, I have a problem with the scour plugin.
When saving an icon with your settings sometimes the size is 4 ,1 KiB and other times it is 2,6KiB.
Debugging it, I see that it is a problem of the package of my distribution, I'll fix it before doing a push again

**Comment by mojamuto** [comment]
Looking at the files, I have several more questions:

1. the icons apps/16 have a larger size, do we have to save them as optimized svg like the rest?
2. Some icons in apps/16 can be ungrouped and a figure appears that I don't find useful, what is it used for?
problema

3.With the options you gave me to save the svg, now the icons are smaller than the ones generated by you, if I look at the size of the 1cestart.svg file in your repository it occupies 9.4kib:


If I open it in inkscape and save it with the options you describe above the size is 7.2kib:
mio

The options I use to save the svg:




Would it be a problem that my icons are smaller?

**Comment by SylEleuth** [comment]
To start the project I took existing Suru+ icon pack and modified it. It was over 2 years ago and since then I've added a lot of other icons (Suru+ was abandoned anyway). In most cases I changed only colors. I did it in an editor and through bash scripts, not even opening Inkscape. Sometimes I see in a code that "old" icons require rework but there are other things to do so it's not a priority.

1. Some icons have 1px padding, some not so I decided to make some rules and one them is a padding when an icon is symmetrical. When it's not and its for example wider there can be an exception. Some app/16 icons are used in panel or in a tray so it's better if they're slightly smaller. I always save them optimized no matter what. 
2. I have no idea what it is and it shouldn't be there. It's one of those icons not made by me. As I can see other Adobe icons have the same rectangle and who knows how many others have some unwanted things. It's not obtrusive so it's not a priority. I've added it to my to-do list.
3. 1cestar.svg is also not made by me. Otherwise I would save it optimized.
4. If Your icons are smaller in a sense that they take less space that's great.

**Pull request closed without merging**
