### PR TITLE
Yuzu icons

### PR DESCRIPTION
**Pull request by mojamuto**
I have changed the size of the scalable of yuzu, now it is more similar to the one in the repository, I think it fits better with the rest of the icons, I erased the black to leave the shiny one, having more icons is unnecessary.
clean the icon of the folder 16 and also the one of the previous commits that also grouped them

I'm sorry I closed the previous pull request, but when I do a revert to a previous commit it closes itself, I'll find another way to do it if it's bothersome

### CODE REVIEW

**Comment by mojamuto** [comment]
Before you look at this pr, I'm going to look at the nesting of the yuzu 16 mentioned in the old pr

**Comment by mojamuto** [comment]
ok, I reverted changes in app/16, I still don't know why prusaslicer-gcodeviewer takes up more space, but I found another problem with the f3d icon in app/16 (I'll open an issue to explain it and how to deal with it ).

The problem with the nested groups was that the original yuzu.svg brings them and I didn't realize it, it's already solved.
I have added the dark icon again, but the brighter icon is the default

**Comment by SylEleuth** [comment]
Sorry that it took me some time but I decided today to fix colors of bunch of icons I found "broken" and noticed a huge discrepancy in bases of the icons. Also during the day I'm using bright desktop theme and bright icons don't look good on it (too much blending) and while I have in plans to make a dark version of icons for bright desktops I decided to rework bases and I (re)created 4 icons - 2 dark and 2 bright. I'll put them in a new folder named "templates" located in top directory. I will add description how to use them but not today. Could You use them from now on, starting with Yuzu icons? I will push templates tomorrow (probably) because I want to look at them with a fresh eye.
Also while saving 16 icons could You use "Remove unused IDs" option? It decreases a size of the file and if icon has unused IDs, they should be removed anyway.

**Comment by mojamuto** [comment]
Of course, take the time you need.
I will redo it with the templates when I add them

**Comment by SylEleuth** [comment]
Thank You.

**Pull request merged**
